# Generated by Django 6.0.1 on 2026-02-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diary',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
